### ISSUE TITLE
List response with no UTF8 capability

### ISSUE THREAD

**Issue by tolikbotov** [yahoo/imapnio#170]
## Description
I have an ICloud account. I named a folder by 'Dubai Co Setup & Real Estate'. 

ICloud server returns this name like 'Dubai Co Setup &- Real Estate', i.e. it encodes '&' to '&-'.

'com.sun.mail.imap.protocol.ListInfo:99' has support such names, but it relates on 'utf8' support flag.

I believe, this flag is set if an imap server has 'UTF8' capability. But Library do nothing to detect it.

## Expected Behavior

I believe, library should detect 'UTF8' support and if it's missing set flag 'utf8' in IMAPResponse as 'false'.

## Actual Behavior
Library ignores capability and set supportsUtf8 as true in any case.

## Possible Fix
Library should replace ImapClientRespDecoder or provide a way to tell it - utf8 is not supported.

## Steps to Reproduce
1. Take icloud imap account
2. Create folder with name, like 'abs & zxc'
3. List folders, you will see 'abs &- zxc'. SHould be 'abs & zxc'.

## Context
I want to see right folder name.

## Your Environment
* Version used: "com.yahoo.imapnio" % "imapnio.core" % "5.0.14"

**Comment by tolikbotov** [comment]
Oh I missed something? Can you help?

**Comment by tolikbotov** [comment]
My bad, i used Imap Java 1.6.2 which is not supported by you i guess.

**Comment by nvsnvikram** [comment]
what are the differences in Java mail 1.6.2. I would expect minor incompatibilites.

**Comment by nvsnvikram** [comment]
Btw, can you demonstrate this with a test? This is imap utf-7 encoded folder name: "Dubai Co Setup &- Real Estate". List folder should have removed "-" and returned the actual folder name: "Dubai Co Setup & Real Estate".
