### ISSUE TITLE
How many threads in IMAPClient is needed per mailbox ?

### ISSUE THREAD

**Issue by prakash-premkumar** [yahoo/imapnio#33]
Hi, 

I'm using imapnio to poll the mailboxes for incoming mails.

The IMAPClient class takes the number of threads as a parameter.
I want to go to IDLE state on all the mailboxes and get notified when the mailbox receives a mail.

if I create a client with 1 thread: i.e

IMAPClient client = new IMAPClient(1);
how many mailboxes/accounts can it handle ?
I want to go to IDLE state for each account.

Thanks for your help.

**Comment by krdev** [comment]
That totally depends on how many threads you want to use for this, a good approximation is the number of cores you have in your CPU.
