### ISSUE TITLE
IMAPConnectionListener onDisconnect() is not called after timeout

### ISSUE THREAD

**Issue by prakash-premkumar** [yahoo/imapnio#34]
Hi, 
I'm using the imapnio api.

Here's the code that creates a session:

> properties.setProperty(IMAPSession.CONFIG_CONNECTION_TIMEOUT_KEY, "300000");  //5 mins
> 
> properties.setProperty(IMAPSession.CONFIG_IMAP_TIMEOUT_KEY, 180000); //3 mins
> 
>  session =  imapClient.createSession(new URI(serverUrl), properties, new IMAPConnectionListenerImpl(imapClient), logManager);

the IMAPConnenctionListenerImpl implements com.lafaspot.imapnio.listener.IMAPConnectionListener interface.

The onDisconnect() method in that interface is not being called due to timeout.

Can you please help me fix it ?

**Comment by jui8wang** [comment]
Please upgrade to latest version and use the future framework.
