### ISSUE TITLE
Maven Could not resolve dependency 2.0.0.0

### ISSUE THREAD

**Issue by sergeymild** [yahoo/imapnio#51]
Writing in pom.xml
```xml
<dependency>
            <groupId>com.github.krdev.imapnio</groupId>
            <artifactId>imapnio.core</artifactId>
            <version>2.0.0</version>
</dependency>
```
And getting an error: Failure to find com.github.krdev.imapnio:imapnio.core:jar:2.0.0 in https://repo.maven.apache.org/maven2

**Comment by grexe** [comment]
This is because 2.0.0 has not been released yet, unfortunately, although the main page says so.
Can the author please deploy a release 2.0.0 to Maven central or here for download?
I want to use the project but need an official release.

**Comment by jui8wang** [comment]
Could u try following , we will soon update the readme with the following changes.
            <dependency>
                <groupId>com.yahoo.imapnio</groupId>
                <artifactId>imapnio.core</artifactId>
                <version>2.0.7</version>
            </dependency>

**Comment by grexe** [comment]
Ok thanks, Maven repos seem to be still out of sync and I could not retrieve it locally, but it it is here:
https://mvnrepository.com/artifact/com.yahoo.imapnio/imapnio.core/2.0.7

**Comment by jui8wang** [comment]
The official documentation from JFrog JCenter is in: https://bintray.com/bintray/jcenter

Hit the SET ME UP! button on the upper right corner to point the snapshot to the jcenter url.

**Comment by grexe** [comment]
Thanks @jui8wang that did it, my fault, fixed the configuration and it could retrieve the dependencies, now I have to adjust the code…
